### ISSUE TITLE
1주차 과제 추가 코멘트

### ISSUE THREAD

**Issue by sunsidew** [daniela-jh/sparta101#2]
쇼핑몰 다양하게 시도하시는 것 자체가 너무 좋습니다! bootstrap을 이용하면 모바일 및 pc 웹 모두 잘 보이는 페이지를 만들기 편리하니 시간 나실때 천천히 살펴봐주세요

https://github.com/daniela-jh/sparta101/blob/61ae1ffb03cadf7fb1c5dce057a5f99c5c6ed173/onepageshop_reactive.html#L31

처럼요 :)

전반적으로 깔끔하고 지적할 곳 없이 잘해주셨습니다. 옥의 티를 애써 찾자면

https://github.com/daniela-jh/sparta101/blob/61ae1ffb03cadf7fb1c5dce057a5f99c5c6ed173/onepageshop_reactive.html#L49

와 같이 style을 직접 주시는 것을 가능한 지양하시고 id나 클래스를 할당, 거기에 css를 주는 방식을 권장드립니다.
태그들이 id/class를 많이, 대부분 가지고 있는게 나쁘지 않아요!

<hr>

나홀로 메모장에 대해서도 전체적으로 깔끔하시고

https://github.com/daniela-jh/sparta101/blob/61ae1ffb03cadf7fb1c5dce057a5f99c5c6ed173/lonelymemo.html#L27

margin-left/right auto사용도 좋네요! 깔끔하고 너무 좋습니다 :)

https://github.com/daniela-jh/sparta101/blob/61ae1ffb03cadf7fb1c5dce057a5f99c5c6ed173/lonelymemo.html#L55

와 같이 껍데기 상태로 만들어놓는 a tag의 경우에는 `<a href="#">`으로 해주시면 눌러도 불필요한 동작이 없어 자주 쓰기도 하는 방식이니 가볍게 참고해주세요 :)

**Comment by daniela-jh** [comment]
확인했습니다. 감사합니다 지웅 튜터님 :)
>id나 클래스를 할당, 거기에 css를 주는 방식
2주차 과제에 적용했습니다!
