### ISSUE TITLE
3주차 코멘트

### ISSUE THREAD

**Issue by sunsidew** [daniela-jh/sparta101#3]
https://github.com/daniela-jh/sparta101/blob/f8eaebe22fcd7fcd732a6b7c8abdb531f1f081ac/onepageshop_w3.html#L192 의 onchange 를 쓰셨네요. 변경할때마다 체크하려고 하신 것 좋습니다! 다만 아마 잘 작동하지 않으셨을텐데요. onchange는 보통 option 태그의 변동이나 라디오 버튼, 체크박스등에 주로 쓰게 됩니다. 변경 확인과 관련한 부분은 다음 수업 시간에 자세히 말씀드릴게요 :)

https://github.com/daniela-jh/sparta101/blob/f8eaebe22fcd7fcd732a6b7c8abdb531f1f081ac/onepageshop_w3.html#L111도 onchange로 만드셨던 telcheck 함수와 코드가 같죠? telcheck함수를 불러주시는걸로 간단하게 만들 수 있을거 같아요. 

center tag는 HTML5에서 더 쓰지 않는 코드입니다. 
쉽게 말해 9이하의 옛날 인터넷 익스플로러 같은 경우에나 가능한 태그기에 현재는 css를 써서 정렬하는 것이 공식가이드라고 보시면 됩니다. 관련한 부분은 https://developer.mozilla.org/ko/docs/Web/HTML/Element/center를, HTML5에 대해서는 https://ko.wikipedia.org/wiki/HTML5를 참고하시면 좋아요.

$(document).ready(function() { 잘 이해하고 써주셨어요.

잘 해주셨어요 👍

**Comment by daniela-jh** [comment]
Thank you :)
